Repository LikeLion-FE-JS-Project19/market-karly, pull requests merged in 2023-02, with the labels that each got.

#31 [#13] [FEATURE] header 마크업
  client/assets/header/ic-baby.svg
  client/assets/header/ic-bread.svg
  client/assets/header/ic-cart.svg
  client/assets/header/ic-coffee.svg
  client/assets/header/ic-cook.svg
  client/assets/header/ic-cosmetics.svg
  client/assets/header/ic-default.svg
  client/assets/header/ic-detergent.svg
  client/assets/header/ic-dog.svg
  client/assets/header/ic-down.svg
  client/assets/header/ic-food.svg
  client/assets/header/ic-fruit.svg
  client/assets/header/ic-gift.svg
  client/assets/header/ic-hamburger.svg
  client/assets/header/ic-health.svg
  client/assets/header/ic-heart.svg
  client/assets/header/ic-home-appliances.svg
  client/assets/header/ic-location.svg
  client/assets/header/ic-meet.svg
  client/assets/header/ic-new-tag.svg
  client/assets/header/ic-oil.svg
  client/assets/header/ic-salad.svg
  client/assets/header/ic-sea-food.svg
  client/assets/header/ic-search.svg
  client/assets/header/ic-shampoo.svg
  client/assets/header/ic-snack.svg
  client/assets/header/ic-traditional-liquor.svg
  client/assets/header/ic-travel.svg
  client/assets/header/ic-vegetable.svg
  client/assets/header/ic-wine.svg
  client/assets/header/logo-kurly.svg
  client/css/style.css
  client/index.html
  client/js/main.js
  client/js/seokwon.js
Labels: ✨ feature

#36 [#8] 메인화면 광고배너 팝업 영역 작업
  .eslintrc.js
  client/assets/common/ic-close.svg
  client/assets/common/ic-vector-bottom.svg
  client/assets/common/ic-vector-top.svg
  client/assets/modal/main-modal.jpg
  client/css/style.css
  client/index.html
  client/js/kyungseob.js
  client/js/main.js
Labels: ✨ feature

#41 [#39] [BUG] 메인 배너 캐로셀 페이지네이션 CSS 버그 #1
  client/css/header.css
  client/css/style.css
  client/index.html
  client/js/juhee.js
  client/js/seeun.js
Labels: 🐛 bug

#47 [🐛bug] side-bar 네이밍 수정, 상단바,메인모달 z-index 수정 #45
  client/css/header.css
  client/css/main-modal.css
  client/index.html
Labels: 🐛 bug

#49 [#48] [BUG] footer 리팩토링
  client/index.html
  client/js/jiwon.js
  client/js/main.js
Labels: 🐛 bug

#51 [#50][BUG] 파일 경로 수정
  client/cart.html
  client/css/header.css
  client/css/main-modal.css
  client/css/style.css
  client/index.html
  client/js/common/common.js
  client/js/main.js
  client/product-detail.html
  client/product-list.html
Labels: 🐛 bug

#52 [#35] [FEATURE] 상품 상세 페이지 상품 설명 영역 작업
  client/assets/product-detail/goods_point.png
  client/assets/product-detail/ic-disabled-alarm.svg
  client/assets/product-detail/ic-disabled-heart.svg
  client/assets/product-detail/ic-heart.svg
  client/assets/product-detail/ic-minus.svg
  client/assets/product-detail/ic-plus.svg
  client/assets/product-detail/why-carly.png
  client/css/header.css
  client/css/product-detail.css
  client/js/common/common.js
  client/js/product-detail.js
  client/js/seeun.js
  client/product-detail.html
Labels: ✨ feature

#54 [#37] [FEATURE] 상세 페이지 문의하기 영역 작업
  client/assets/product-detail/ic-answer.svg
  client/assets/product-detail/ic-cancel.svg
  client/assets/product-detail/ic-check.svg
  client/assets/product-detail/ic-lock.svg
  client/assets/product-detail/ic-question.svg
  client/css/footer.css
  client/css/product-detail.css
  client/js/common/common.js
  client/js/jiwon.js
  client/js/main.js
  client/js/product-detail.js
  client/product-detail.html
  server/db/data.json
Labels: ✨ feature

#56 [#42] [FEATURE] 상품 상세페이지 상품 후기 영역
  client/assets/product-detail/arrow.svg
  client/assets/product-detail/cancel.svg
  client/css/product-detail.css
  client/js/juhee.js
  client/js/product-detail.js
  client/product-detail.html
Labels: ✨ feature

#57 [#53] [REFACTORING] main, product-detail 페이지 리팩토링
  client/assets/product-detail/goods-point.png
  client/assets/product-detail/goods_point.png
  client/assets/product-detail/ic-disabled-heart.svg
  client/assets/product-detail/ic-minus.svg
  client/assets/product-detail/ic-plus.svg
  client/assets/product-detail/why-carly.png
  client/assets/product/bacon/detail-banner.jpg
  client/assets/product/bacon/detail-info.jpg
  client/assets/product/bacon/detail-view.jpg
  client/assets/product/bacon/detail_banner.jpg
  client/assets/product/bacon/detail_info.jpg
  client/assets/product/bacon/detail_view.jpg
  client/assets/product/bacon/thumbnail.jpg
  client/assets/product/brownrice/thumbnail.png
  client/assets/product/detergent/thumbnail.png
  client/assets/product/jukkumi/detail-banner.jpg
  client/assets/product/jukkumi/detail-info.jpg
  client/assets/product/jukkumi/detail-view.jpg
  client/assets/product/jukkumi/detail_banner.jpg
  client/assets/product/jukkumi/detail_info.jpg
  client/assets/product/jukkumi/detail_view.jpg
  client/assets/product/jukkumi/thumbnail.jpg
  client/assets/product/kangnam/detail-banner.jpg
  client/assets/product/kangnam/detail-info.jpg
  client/assets/product/kangnam/detail-view.jpg
  client/assets/product/kangnam/detail_banner.jpg
  client/assets/product/kangnam/detail_info.jpg
  client/assets/product/kangnam/detail_view.jpg
  client/assets/product/kangnam/thumbnail.jpg
  client/assets/product/suncushion/thumbnail.png
  client/assets/product/tangtang/detail-banner.jpg
  client/assets/product/tangtang/detail-info.jpg
  client/assets/product/tangtang/detail-view.jpg
  client/assets/product/tangtang/detail_banner.jpg
  client/assets/product/tangtang/detail_info.jpg
  client/assets/product/tangtang/detail_view.jpg
  client/assets/product/tangtang/thumbnail.jpg
  client/assets/product/ubuho/detail-banner.jpg
  client/assets/product/ubuho/detail-info.jpg
  client/assets/product/ubuho/detail-view.jpg
  client/assets/product/ubuho/detail_banner.jpg
  client/assets/product/ubuho/detail_info.jpg
  client/assets/product/ubuho/detail_view.jpg
  client/assets/product/ubuho/thumbnail.jpg
  client/css/product-detail.css
  client/css/theme.css
  client/index.html
  client/js/common/common.js
  client/js/main.js
  client/js/seeun.js
  client/product-detail.html
  server/db/data.json
Labels: 🔨 enhancement

#60 [#58] [FEATURE] head title, meta 태그 추가
  client/cart.html
  client/index.html
  client/js/product-detail.js
  client/js/seeun.js
  client/product-detail.html
  client/product-list.html
Labels: ✨ feature

#66 [#65] [🐛 bug] 상품 후기 작성하기 버튼 오류 해결
  client/css/product-detail.css
  client/js/product-detail.js
  client/product-detail.html
Labels: 🐛 bug

#64 [#61] [REFACTORING] 문의하기 영역 리팩토링
  client/assets/common/ic-check.svg
  client/assets/product-detail/ic-check.svg
  client/css/product-detail.css
  client/js/jiwon.js
  client/js/product-detail.js
  client/product-detail.html
  server/db/data.json
Labels: 🔨 enhancement

#55 [#40] [FEATURE] 장바구니 페이지 영역
  client/assets/cart/ic-cancel.svg
  client/assets/cart/ic-checked-false.svg
  client/assets/cart/ic-checked-true.svg
  client/assets/cart/ic-cold.svg
  client/assets/cart/ic-frozen.svg
  client/assets/cart/ic-temperature.svg
  client/assets/product/bacon/detail-banner.jpg
  client/assets/product/jukkumi/detail-banner.jpg
  client/assets/product/kangnam/detail-banner.jpg
  client/assets/product/tangtang/detail-banner.jpg
  client/assets/product/ubuho/detail-banner.jpg
  client/cart.html
  client/css/cart.css
  client/css/normalize.css
  client/css/product-list.css
  client/index.html
  client/js/cart.js
  client/js/kyungseob.js
  client/product-detail.html
  client/product-list.html
Labels: ✨ feature

#69 [#68][Bug] 상품 리스트 머지 후 버그 수정
  client/css/product-list.css
  client/js/jiwon.js
  client/js/seeun.js
  client/js/seokwon.js
  client/product-list.html
  server/db/data.json
Labels: 🐛 bug

#71 [#70] [🐛 bug] footer 리팩토링2
  client/cart.html
  client/css/footer.css
  client/css/product-detail.css
  client/js/common/common.js
  client/js/jiwon.js
  client/js/main.js
  client/js/product-detail.js
  client/lib/dom/index.js
  client/product-list.html
Labels: 🐛 bug

#74 [#67] [REFACTOR] 상품 상세페이지, 메인페이지 리팩토링
  client/index.html
  client/js/juhee.js
  client/product-detail.html
  server/db/data.json
Labels: 🔨 enhancement

#75 [#61] [REFACTORING] 문의하기 영역 리팩토링
  client/css/product-detail.css
  client/js/jiwon.js
Labels: 🔨 enhancement

#76 [#73] [REFACTORING] 메인모달, 장바구니 영역 리팩토링
  client/cart.html
  client/css/main-modal.css
  client/index.html
  client/js/cart.js
  client/js/kyungseob.js
  client/js/main.js
Labels: 🔨 enhancement

#77 [#61] [REFACTORING] 문의하기 영역 리팩토링
  client/js/jiwon.js
  client/js/seokwon.js
  client/lib/utils/axios.js
  client/lib/utils/index.js
  client/lib/utils/memo.js
  client/lib/utils/storage.js
  client/lib/utils/tiger.js
Labels: 🔨 enhancement

#78 [#72] 리스트페이지 리팩토링
  client/css/header.css
  client/css/product-list.css
  client/js/seokwon.js
  client/product-list.html
Labels: 🔨 enhancement

#79 [#62] [BUG] 메인 캐로셀 키보드 작동 버그
  client/css/main-modal.css
  client/css/style.css
  client/index.html
  client/js/juhee.js
  client/js/kyungseob.js
  client/js/main.js
  client/js/seeun.js
Labels: 🐛 bug

#81 [#80][BUG] 사이드 캐로셀 이미지 파일 경로 수정
  client/index.html
Labels: 🐛 bug

#83 [#61] [REFACTORING] 문의하기 영역 리팩토링
  client/css/product-detail.css
  client/js/jiwon.js
  client/js/product-detail.js
  server/db/data.json
Labels: 🔨 enhancement

#84 [#82] [REFACTORING] 리팩토링
  client/assets/main/banner01.jpg
  client/assets/main/banner02.jpg
  client/assets/main/banner03.jpg
  client/assets/main/banner04.jpg
  client/assets/main/line-banner.png
  client/cart.html
  client/css/footer.css
  client/css/header.css
  client/css/style.css
  client/index.html
  client/product-detail.html
  client/product-list.html
Labels: 🔨 enhancement

#88 [🔨 refactor] 리스트 토글기능 오류 해결 #86
  client/cart.html
  client/css/cart.css
  client/js/kyungseob.js
  client/js/main.js
Labels: 🔨 enhancement

#90 [#87][REFACTOR] 캐로셀 동적 구현
  client/css/style.css
  client/index.html
  client/js/main.js
  client/js/seokwon.js
  client/product-list.html
Labels: 🔨 enhancement

#89 [#85] [BUG] 상품 디테일 페이지 버그
  client/css/header.css
  client/css/product-detail.css
  client/js/product-detail.js
  client/js/seeun.js
  client/product-detail.html
Labels: 🐛 bug

#91 [#61] [REFACTORING] 문의하기 영역 리팩토링
  client/js/jiwon.js
  client/js/product-detail.js
  server/db/data.json
Labels: 🔨 enhancement
